name: Deploy FastAPI App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run tests
      run: pytest

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}  # Replace with your Docker Hub username
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Replace with your Docker Hub password
      run: |
        echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin  # Replace with your Docker Hub password

    # Step 6: Build and push Docker image
    - name: Build and push Docker image
      env:
        DOCKER_IMAGE_NAME: kibonku/mlops_assignment  # Replace with your Docker image name
      run: |
        docker build -t $DOCKER_IMAGE_NAME .  
        docker push $DOCKER_IMAGE_NAME

    # Step 7: Deploy to Heroku (or any other service)
    # Replace this with your deployment service's specific commands.
    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main'
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Replace with your Heroku API key
      run: |
        # Example for Heroku deployment
        heroku container:login
        heroku container:push web --app your-heroku-app-name  # Replace with your Heroku app name
        heroku container:release web --app your-heroku-app-name  
